### PR TITLE
Switched to systemd to allow latest versions of DSU/OMSA to run

### LINKED ISSUE #9: Can't start srvadmin services on latest build
I haven't dug deep into this yet, but there appears to be a regression on the `latest` build. I notivced when no controllers were detected by `omreport storage controller`. It looks like the srvadmin services can't be started in `latest` but work fine in `dsu-1.5.3`:

```
$ sudo docker run --rm -ti --privileged --net=host -v /dev:/dev kamermans/docker-openmanage:latest bash -c "srvadmin-services.sh status"
#exits immediately with no output
$ sudo docker run --rm -ti --privileged --net=host -v /dev:/dev kamermans/docker-openmanage:dsu-1.5.3 bash -c "srvadmin-services.sh status"
dell_rbu (module) is running
ipmi driver is running
dsm_sa_datamgrd is stopped
dsm_sa_eventmgrd is stopped
dsm_sa_snmpd is stopped
dsm_om_connsvcd is stopped
```

On `dsu-1.5.3` I can use `srvadmin-services.sh status` to start the other services (e.g. `dsm_sa_datamgrd`), on `latest` nothing happens.

### PR DESCRIPTION
**Pull request by kamermans**
This PR switches the init system to systemd since all the Dell services now require it.  I've moved the init script that handles SNMP configuration to a custom systemd service.  All of the services that I've tested seem to work OK.

This should fix #9 

@shane-axiom can you try this image: `kamermans/docker-openmanage:dsu-1.6.0` and see if it's working for you?

> Note that you will need to start the container in daemon mode and connect to it, otherwise `systemd` will not start!  Also, I've added a volume mount `-v /sys/fs/cgroup:/sys/fs/cgroup:ro`, which is required to use `systemd` in the container.  *This version will only run on a host that is running `systemd`*.

### CODE REVIEW

**Comment by shane-axiom** [comment]
@kamermans Yeah, seems to work! Unfortunate that you can't run `dsu` directly anymore and have to start up a daemonized image first, but I couldn't easily find a way to start systemd first using `ENTRYPOINT`.

**Comment by kamermans** [comment]
Yeah, the script checks pid 1 to see if it contains `systemd`, but when I fake that, the init scripts all fail.  I could port all the init scripts back to sysV, and that would probably work, but it seems very fragile.  Perhaps if we fake the pid 1 name and then start systems in the background, then sleep for a second to let the services start, then start `dsu` - that might work.

**Comment by shane-axiom** [comment]
I think I have anothet option for you to consider, need a few hours to put something together though

**Comment by shane-axiom** [comment]
@kamermans Please take a look at https://github.com/kamermans/docker-openmanage/pull/11

**Comment by kamermans** [comment]
Thanks for the help with this @shane-axiom - I had a bunch of cleanup stuff in this PR that I wanted to keep, so I've pulled in your entrypoint and the suggested `systemctl` replacement here.  Can you give `kamermans/docker-openmanage:dsu-1.6.0` another spin?  It seems to work in both command/`dsu` mode and daemon mode, with dynamic SNMP configuration working as before.

File: resources/entrypoint.sh [hunk 1]
```diff
@@ -17,7 +19,14 @@ if [ "x$SNMP_TRAP_DEST" != "x" ]; then
...
 fi
 
-/etc/init.d/snmpd start
-srvadmin-services.sh restart
+# Run any passed commands
+if [ "$#" -gt 0 ]; then
+    # Start Dell services
+    echo "Starting Dell services, this may take a few minutes..."
+    systemctl start snmpd.service
+    srvadmin-services.sh start
```
Comment (shane-axiom) [inline resources/entrypoint.sh]: I notice that `srvadmin-services.sh start` is only run in the entrypoint script if `CMD` is set. Probably not an issue since a default `CMD` is set in the Dockerfile, but for clarity would it make sense to move the service startup outside of the `CMD` eval block?

**Comment by shane-axiom** [comment]
@kamermans Looks good to me, I added one comment/question on the service startup in the entrypoint, but :+1:

File: resources/entrypoint.sh (hunk 1 above)
Comment (kamermans) [reply resources/entrypoint.sh]: Good point - I had considered this, then I tried to see if it was possible not to end up in that block, but it seemed impossible.  I think I'll the "start services" portion out and just leave the eval statement in there.
